server:
  port: 8081

spring:
  application:
    name: banking-mcp-server
  ai:
    mcp:
      server:
        name: banking-mcp-server
        version: 0.0.1
        protocol: STREAMABLE
        annotation-scanner:
          enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: bankuser
    password: bankpass

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true      
