spring:
  application:
    name: mcp-client

  ai:
    mcp:
      client:
        streamable-http:
          connections:
            server:
              url: http://localhost:8081/
            server2:
              url: http://localhost:8082/  